
    create table public.bookings (
       id int8 generated by default as identity,
        end_booking timestamp not null,
        start_booking timestamp not null,
        status varchar(255),
        booker_id int8 not null,
        item_id int8 not null,
        primary key (id)
    );

    create table public.comments (
       id int8 generated by default as identity,
        created timestamp,
        text varchar(255) not null,
        author_id int8,
        item_id int8,
        primary key (id)
    );

    create table public.item_request (
       id int8 generated by default as identity,
        created timestamp,
        description varchar(255),
        creator_id int8,
        primary key (id)
    );

    create table public.items (
       id int8 generated by default as identity,
        available boolean,
        description varchar(255) not null,
        name varchar(255) not null,
        request_id int8,
        item_request_id int8,
        owner_id int8,
        primary key (id)
    );

    create table public.users (
       id int8 generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists public.users 
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists public.bookings 
       add constraint FKc9bnqnreuuvddcscmp59fowih 
       foreign key (booker_id) 
       references public.users;

    alter table if exists public.bookings 
       add constraint FKbtv44e8p4a4pq8hfuakjbtfpc 
       foreign key (item_id) 
       references public.items;

    alter table if exists public.comments 
       add constraint FKn2na60ukhs76ibtpt9burkm27 
       foreign key (author_id) 
       references public.users;

    alter table if exists public.comments 
       add constraint FKkbkydvf8j8tfuego2iqxntwv2 
       foreign key (item_id) 
       references public.items;

    alter table if exists public.item_request 
       add constraint FKpb32954aad3v6p41a88ws565q 
       foreign key (creator_id) 
       references public.users;

    alter table if exists public.items 
       add constraint FKfwcxae59jr09r2r867pw74xu9 
       foreign key (item_request_id) 
       references public.item_request;

    alter table if exists public.items 
       add constraint FKe37yi0i6rmaqcqickvb1vty22 
       foreign key (owner_id) 
       references public.users;

    alter table if exists public.items 
       add constraint FK3im6l4d6ylks6u3jn7xemy3pp 
       foreign key (request_id) 
       references public.item_request;

    create table public.bookings (
       id int8 generated by default as identity,
        end_booking timestamp not null,
        start_booking timestamp not null,
        status varchar(255),
        booker_id int8 not null,
        item_id int8 not null,
        primary key (id)
    );

    create table public.comments (
       id int8 generated by default as identity,
        created timestamp,
        text varchar(255) not null,
        author_id int8,
        item_id int8,
        primary key (id)
    );

    create table public.item_request (
       id int8 generated by default as identity,
        created timestamp,
        description varchar(255),
        creator_id int8,
        primary key (id)
    );

    create table public.items (
       id int8 generated by default as identity,
        available boolean,
        description varchar(255) not null,
        name varchar(255) not null,
        request_id int8,
        item_request_id int8,
        owner_id int8,
        primary key (id)
    );

    create table public.users (
       id int8 generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists public.users 
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists public.bookings 
       add constraint FKc9bnqnreuuvddcscmp59fowih 
       foreign key (booker_id) 
       references public.users;

    alter table if exists public.bookings 
       add constraint FKbtv44e8p4a4pq8hfuakjbtfpc 
       foreign key (item_id) 
       references public.items;

    alter table if exists public.comments 
       add constraint FKn2na60ukhs76ibtpt9burkm27 
       foreign key (author_id) 
       references public.users;

    alter table if exists public.comments 
       add constraint FKkbkydvf8j8tfuego2iqxntwv2 
       foreign key (item_id) 
       references public.items;

    alter table if exists public.item_request 
       add constraint FKpb32954aad3v6p41a88ws565q 
       foreign key (creator_id) 
       references public.users;

    alter table if exists public.items 
       add constraint FKfwcxae59jr09r2r867pw74xu9 
       foreign key (item_request_id) 
       references public.item_request;

    alter table if exists public.items 
       add constraint FKe37yi0i6rmaqcqickvb1vty22 
       foreign key (owner_id) 
       references public.users;

    alter table if exists public.items 
       add constraint FK3im6l4d6ylks6u3jn7xemy3pp 
       foreign key (request_id) 
       references public.item_request;

    create table public.bookings (
       id int8 generated by default as identity,
        end_booking timestamp not null,
        start_booking timestamp not null,
        status varchar(255),
        booker_id int8 not null,
        item_id int8 not null,
        primary key (id)
    );

    create table public.comments (
       id int8 generated by default as identity,
        created timestamp,
        text varchar(255) not null,
        author_id int8,
        item_id int8,
        primary key (id)
    );

    create table public.item_request (
       id int8 generated by default as identity,
        created timestamp,
        description varchar(255),
        creator_id int8,
        primary key (id)
    );

    create table public.items (
       id int8 generated by default as identity,
        available boolean,
        description varchar(255) not null,
        name varchar(255) not null,
        request_id int8,
        item_request_id int8,
        owner_id int8,
        primary key (id)
    );

    create table public.users (
       id int8 generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists public.users 
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists public.bookings 
       add constraint FKc9bnqnreuuvddcscmp59fowih 
       foreign key (booker_id) 
       references public.users;

    alter table if exists public.bookings 
       add constraint FKbtv44e8p4a4pq8hfuakjbtfpc 
       foreign key (item_id) 
       references public.items;

    alter table if exists public.comments 
       add constraint FKn2na60ukhs76ibtpt9burkm27 
       foreign key (author_id) 
       references public.users;

    alter table if exists public.comments 
       add constraint FKkbkydvf8j8tfuego2iqxntwv2 
       foreign key (item_id) 
       references public.items;

    alter table if exists public.item_request 
       add constraint FKpb32954aad3v6p41a88ws565q 
       foreign key (creator_id) 
       references public.users;

    alter table if exists public.items 
       add constraint FKfwcxae59jr09r2r867pw74xu9 
       foreign key (item_request_id) 
       references public.item_request;

    alter table if exists public.items 
       add constraint FKe37yi0i6rmaqcqickvb1vty22 
       foreign key (owner_id) 
       references public.users;

    alter table if exists public.items 
       add constraint FK3im6l4d6ylks6u3jn7xemy3pp 
       foreign key (request_id) 
       references public.item_request;

    create table public.bookings (
       id int8 generated by default as identity,
        end_booking timestamp not null,
        start_booking timestamp not null,
        status varchar(255),
        booker_id int8 not null,
        item_id int8 not null,
        primary key (id)
    );

    create table public.comments (
       id int8 generated by default as identity,
        created timestamp,
        text varchar(255) not null,
        author_id int8,
        item_id int8,
        primary key (id)
    );

    create table public.item_request (
       id int8 generated by default as identity,
        created timestamp,
        description varchar(255),
        creator_id int8,
        primary key (id)
    );

    create table public.items (
       id int8 generated by default as identity,
        available boolean,
        description varchar(255) not null,
        name varchar(255) not null,
        request_id int8,
        item_request_id int8,
        owner_id int8,
        primary key (id)
    );

    create table public.users (
       id int8 generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists public.users 
       add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);

    alter table if exists public.bookings 
       add constraint FKc9bnqnreuuvddcscmp59fowih 
       foreign key (booker_id) 
       references public.users;

    alter table if exists public.bookings 
       add constraint FKbtv44e8p4a4pq8hfuakjbtfpc 
       foreign key (item_id) 
       references public.items;

    alter table if exists public.comments 
       add constraint FKn2na60ukhs76ibtpt9burkm27 
       foreign key (author_id) 
       references public.users;

    alter table if exists public.comments 
       add constraint FKkbkydvf8j8tfuego2iqxntwv2 
       foreign key (item_id) 
       references public.items;

    alter table if exists public.item_request 
       add constraint FKpb32954aad3v6p41a88ws565q 
       foreign key (creator_id) 
       references public.users;

    alter table if exists public.items 
       add constraint FKfwcxae59jr09r2r867pw74xu9 
       foreign key (item_request_id) 
       references public.item_request;

    alter table if exists public.items 
       add constraint FKe37yi0i6rmaqcqickvb1vty22 
       foreign key (owner_id) 
       references public.users;

    alter table if exists public.items 
       add constraint FK3im6l4d6ylks6u3jn7xemy3pp 
       foreign key (request_id) 
       references public.item_request;
