DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_USER_ID UNIQUE (id),
    CONSTRAINT UQ_USER_EMAIL unique (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    name        VARCHAR(255)                                   NOT NULL,
    description VARCHAR(255)                                   NOT NULL,
    available   BOOLEAN                                        NOT NULL,
    owner_id    BIGINT REFERENCES users (id) ON DELETE CASCADE,
    request     BOOLEAN                                        NOT NULL,
    CONSTRAINT PK_ITEM_ID UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    start_booking TIMESTAMP WITHOUT TIME ZONE                     NOT NULL,
    end_booking   TIMESTAMP WITHOUT TIME ZONE                     NOT NULL,
    item_id       INTEGER REFERENCES items (id) ON DELETE CASCADE ,
    booker_id     INTEGER REFERENCES users (id) ON DELETE CASCADE ,
    status        VARCHAR(25)                                     NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    text      TEXT                                            NOT NULL,
    item_id   INTEGER REFERENCES items (id) ON DELETE CASCADE ,
    author_id INTEGER REFERENCES users (id) ON DELETE CASCADE ,
    created   TIMESTAMP WITHOUT TIME ZONE                     NOT NULL
)
