DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL unique (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    owner_id    INTEGER                                 NOT NULL,
    request_id  INTEGER,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (owner_id)
        REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_booking TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_booking   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    INTEGER                                 NOT NULL,
    booker_id  INTEGER                                 NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booker_id FOREIGN KEY (booker_id)
        REFERENCES users (id),
    CONSTRAINT fk_item_id FOREIGN KEY (item_id)
        REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      TEXT                                    NOT NULL,
    item_id   INTEGER                                 NOT NULL,
    author_id INTEGER                                 NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_author_id FOREIGN KEY (author_id)
        REFERENCES users (id),
    CONSTRAINT fk_item_id_comments FOREIGN KEY (item_id)
        REFERENCES items (id)
)
